In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:\OneDrive\Documents\Downloads\Hospital_Project\hospitals.csv")

In [3]:
df.head()

,hospital_id,hospital_name,city,ownership_type,bed_capacity,launch_year
0,1,MedNova Hospital - Hyderabad,Hyderabad,Private,420,2009
1,2,MedNova Hospital - Bengaluru,Bengaluru,Private,360,2012
2,3,MedNova Hospital - Chennai,Chennai,Trust,310,2014
3,4,MedNova Hospital - Pune,Pune,Private,280,2018
4,5,MedNova Hospital - Mumbai,Mumbai,Private,390,2011

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hospital_id     8 non-null      int64
 1   hospital_name   8 non-null      object
 2   city            8 non-null      object
 3   ownership_type  8 non-null      object
 4   bed_capacity    8 non-null      int64
 5   launch_year     8 non-null      int64
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes

In [5]:
df.isnull().sum()

hospital_id       0
hospital_name     0
city              0
ownership_type    0
bed_capacity      0
launch_year       0
dtype: int64

In [6]:
df["hospital_name"] = df["hospital_name"].str.strip()
df["city"] = df["city"].str.strip()
df["ownership_type"] = df["ownership_type"].str.strip()

In [11]:
len(df)

8

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop_duplicates()

In [12]:
df.dtypes

hospital_id        int64
hospital_name     object
city              object
ownership_type    object
bed_capacity       int64
launch_year        int64
dtype: object

In [13]:
df.head()

,hospital_id,hospital_name,city,ownership_type,bed_capacity,launch_year
0,1,MedNova Hospital - Hyderabad,Hyderabad,Private,420,2009
1,2,MedNova Hospital - Bengaluru,Bengaluru,Private,360,2012
2,3,MedNova Hospital - Chennai,Chennai,Trust,310,2014
3,4,MedNova Hospital - Pune,Pune,Private,280,2018
4,5,MedNova Hospital - Mumbai,Mumbai,Private,390,2011

In [14]:
df.to_csv("cleaned_hospitals.csv", index=False)