In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:\OneDrive\Documents\Downloads\Hospital_Project\lab_results_raw.csv")

In [3]:
df.head()

,lab_id,admission_id,patient_id,test_name,test_value,test_date,result_flag
0,1,2133,11981,CRP,5.99,2023-01-01,Abnormal
1,2,5569,5064,Sodium,2.46,2023-01-01,Normal
2,3,17271,1824,CRP,2.84,2023-01-01,Abnormal
3,4,24486,9939,HbA1c,14.91,2023-01-01,Normal
4,5,21094,8920,Hemoglobin,11.46,2023-01-01,Abnormal

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lab_id        60000 non-null  int64
 1   admission_id  60000 non-null  int64
 2   patient_id    60000 non-null  int64
 3   test_name     60000 non-null  object
 4   test_value    59880 non-null  float64
 5   test_date     60000 non-null  object
 6   result_flag   60000 non-null  object
dtypes: float64(1), int64(3), object(3)
memory usage: 3.2+ MB

In [5]:
df.isnull().sum()

lab_id            0
admission_id      0
patient_id        0
test_name         0
test_value      120
test_date         0
result_flag       0
dtype: int64

In [6]:
df["test_name"] = df["test_name"].str.strip()

df["result_flag"] = df["result_flag"].str.strip()

In [10]:
len(df)

60000

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df = df.drop_duplicates()

In [11]:
df.dtypes

lab_id            int64
admission_id      int64
patient_id        int64
test_name        object
test_value      float64
test_date        object
result_flag      object
dtype: object

In [12]:
df["test_date"] = pd.to_datetime(
    df["test_date"],
    format="mixed",
    dayfirst=True
)

In [14]:
df["result_flag"] = df["result_flag"].str.title()

df["test_name"] = df["test_name"].str.title()

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lab_id        60000 non-null  int64
 1   admission_id  60000 non-null  int64
 2   patient_id    60000 non-null  int64
 3   test_name     60000 non-null  object
 4   test_value    59880 non-null  float64
 5   test_date     60000 non-null  datetime64[ns]
 6   result_flag   60000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 3.2+ MB

In [18]:
df["result_flag"].unique()

array(['Abnormal', 'Normal', 'Critical'], dtype=object)

In [19]:
df["test_value"].isnull().sum()

np.int64(120)

In [20]:
df["test_value"] = df["test_value"].fillna(
    df["test_value"].median()
)

In [21]:
df["test_value"].isnull().sum()

np.int64(0)

In [22]:
df.head()

,lab_id,admission_id,patient_id,test_name,test_value,test_date,result_flag
0,1,2133,11981,Crp,5.99,2023-01-01,Abnormal
1,2,5569,5064,Sodium,2.46,2023-01-01,Normal
2,3,17271,1824,Crp,2.84,2023-01-01,Abnormal
3,4,24486,9939,Hba1C,14.91,2023-01-01,Normal
4,5,21094,8920,Hemoglobin,11.46,2023-01-01,Abnormal

In [24]:
df.to_csv("cleaned_lab_results.csv", index=False)